version: '3'

services:
  telegram-bot:
    build: ./telegram-bot
    container_name: telegram-bot
    ports:
      - "5000:5000"
    networks:
      - my-network

  my-node-app:
    build: ./my-node-app
    container_name: my-node-app
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
