name: Deploy Flask Application

on:
  push:
    branches:
      - Deploy

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Используем self-hosted runner

    steps:
      # Шаг 1: Клонируем код репозитория
      - name: Checkout Code
        uses: actions/checkout@v3

      # Шаг 2: Сборка Docker-образа из Dockerfile
      - name: Build Docker image
        run: docker build -t flask-app:latest .

      # Шаг 3: Остановка и удаление предыдущего контейнера (если существует)
      - name: Stop and remove existing container
        run: |
          docker stop flask-app || true
          docker rm flask-app || true

      # Шаг 4: Запуск нового контейнера
      - name: Run Docker container
        run: |
          docker run -d \
            --name flask-app \
            -p 5000:5000 \
            flask-app:latest
