name: Deploy Flask App

on:
  push:
    branches:
      - Deploy
    paths:
      - 'RESTful API/**'  # Следит за изменениями в директории flask-app
      - '.github/workflows/flask-app.yml'  # Следит за изменениями в директории workflows

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker image
        # Сборка Docker-образа для Flask-приложения. Обратите внимание на кавычки вокруг путей с пробелами
        run: docker build -t flask-app:latest -f "./RESTful API/Dockerfile" "./RESTful API"

      - name: Stop and remove existing container
        # Остановка и удаление предыдущего контейнера flask-app
        run: |
          docker stop flask-app || true
          docker rm flask-app || true

      - name: Run Docker container
        # Запуск контейнера flask-app, подключенного к существующей сети my-network
        run: |
          docker run -d \
            --network my-network \
            --name flask-app \
            -p 5001:5001 \
            flask-app:latest
